# -*- coding: utf-8 -*-
"""5a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsaVIkQjTYdg82mrWXTtGL9FZSsbx889
"""

import numpy as np
import matplotlib.pyplot as plt

# First we will start by loading our dataset
field_values = np.load("scalars_2D.npy")
num_rows, num_cols = field_values.shape

# Defining the threshold valuel.
threshold = 30

# Now we can start to plot our graph
def plot_point(axis, x_coord, y_coord, point_color):
    axis.plot(x_coord, y_coord, marker='o', color=point_color, markersize=5)
    #print(axis.show())

# Initialize the values
fig, axis = plt.subplots(figsize=(8, 8))
axis.set_xlim(-0.5, num_cols - 0.5)
axis.set_ylim(-0.5, num_rows - 0.5)
axis.set_xticks(range(num_cols))
axis.set_yticks(range(num_rows))
axis.grid(True)

# Let's go over our created matrx
for row in range(num_rows - 1):
    #print("row value",row)
    for col in range(num_cols - 1):
        # Calculating  the middle position
        mid_x = col + 0.5
        mid_y = row + 0.5

        # Assign color based on above threshold comparison
        point_color = 'red' if field_values[row, col] > threshold else 'black'
        # print_color.show()

        # We then just plot the graph
        plot_point(axis, mid_x, mid_y, point_color)

plt.gca().invert_yaxis()
plt.show()

